skillMetadata:
  sections:
  - name: Login
    fields:
    - name: host
      type: text
      label: Host adress or ip number
      value: ''
    - name: token
      type: password
      label: Long-Lived Access Tokens
      value: ''
    - name: portnum
      type: number
      label: Port number
      value: 8123
  - name: Options
    fields:
    - name: ssl
      type: checkbox
      label: Use SSL
      value: "false"
    - name: verify
      type: checkbox
      label: Verify SSL Certificate
      value: "true"
    - name: enable_fallback
      type: checkbox
      label: Enable conversation component as fallback
      value: "true"
